### ISSUE TITLE
Icons are blurry

### ISSUE THREAD

**Issue by phw** [ubuntu/gnome-shell-extension-appindicator#101]
Since the latest release icons are a bit blurry if they only come in bitmap format. It also seems they are a bit too large, but I did not compare with the previous version.

![appindicator](https://user-images.githubusercontent.com/29852/32089232-f48af454-bae8-11e7-8a36-3716f2ed4742.png)

**Comment by jhasse** [comment]
Is this also the case with the default GNOME Shell theme?

**Comment by phw** [comment]
Yep, also with default Adwaita theming for the shell:

![appindicators-adwaita](https://user-images.githubusercontent.com/29852/32100862-caa8e98e-bb15-11e7-87c9-886e0e84808a.png)

My guess would be this is because of https://github.com/ubuntu/gnome-shell-extension-appindicator/commit/87db22dccf3a762c3c1ad86ca5e87bda39fbd731

**Comment by phw** [comment]
Yep, I reverted that change locally, and icons look crisper again (see especially the Skype and Synergy icons):

![appindicator-fixed](https://user-images.githubusercontent.com/29852/32100966-503419c0-bb16-11e7-8630-9fec80166bc5.png)

**Comment by jhasse** [comment]
Thanks for the screenshots. I've only tested Dropbox, Steam and Telegram, see https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/68#issuecomment-338324136. I think the +2 needs to be only applied when using a pixbuf. Your Dropbox icon looks like you're using a non-default icon theme, is that correct?

**Comment by jhasse** [comment]
I've updated the icon size to 22px, can you see if that makes them still blurry?

**Comment by phw** [comment]
Not, this makes them just larger and they look awkward:

![bildschirmfoto vom 2017-11-24 10-40-44](https://user-images.githubusercontent.com/29852/33204480-f3a168e4-d103-11e7-9833-aff171633c77.png)

In both cases there are only pixel icons provided. Skype provides 16px and 32 pixel sizes, Synergy 16px and 24 px. But even if I increase it to 24px, the Synergy icon used seems to be the 16px version blown up to 24px.

What's the reason for the `Panel.PANEL_ICON_SIZE + x` at all? In my screenshots you can see that this affects only the pixel icons anyway, all icons that are available as vector icons are displayed in the default `Panel.PANEL_ICON_SIZE` of 16px. So as soon as I set `Panel.PANEL_ICON_SIZE + x` the pixel icons will always look a) blurry and  b) out of place since they are larger than the rest. The only real fix to me seems to avoid using the `+ x`.

**Comment by jhasse** [comment]
Thanks for testing :)

> What's the reason for the Panel.PANEL_ICON_SIZE + x at all?

People find the 16px size to small, see #68.

> But even if I increase it to 24px, the Synergy icon used seems to be the 16px version blown up to 24px.

That's weird, it should use the 24px icon.

> In my screenshots you can see that this affects only the pixel icons anyway, all icons that are available as vector icons are displayed in the default Panel.PANEL_ICON_SIZE of 16px.

Do you mean Dropbox? Please see my previous question: "Your Dropbox icon looks like you're using a non-default icon theme, is that correct?"

Which Skype version do you use? I wan't to reproduce the bluriness and AFAIK Synergy isn't free?

What we definitely should do: Use the higher resolution icons and downscale them, instead of upscaling, if there isn't a perfect match.

**Comment by phw** [comment]
> Your Dropbox icon looks like you're using a non-default icon theme, is that correct?

Yeah, ignore that dropbox icon. I had some custom icons just for that. Removed them now, now it uses the default files.

> Which Skype version do you use? I wan't to reproduce the bluriness and AFAIK Synergy isn't free?

Syngery is GPL, your distribution probably has a package for it. But you can also get just the icon at https://github.com/symless/synergy-core/blob/v1.8.8-stable/res/synergy.ico

For Skype I use the latest [Skype for Linux Preview](https://answers.microsoft.com/en-us/skype/forum/skype_linux-skype_startms-skype_installms/skype-preview-the-most-expressive-skype-ever-is/fc717d17-03ad-4946-bb24-08b131da1840).

>> But even if I increase it to 24px, the Synergy icon used seems to be the 16px version blown up to 24px.

> That's weird, it should use the 24px icon.

I have to correct this, it affects all app indicator icons except dropbox (which seems to do things sepcial anyway). I confused one of the other panel icons with an appindicator.

> People find the 16px size to small, see #68.

Why would I want the app indicator icons to be larger then the rest of my panel icons? That doesn't make much sense.

For some comparisson here is Top Icons Plus with icon size set to the default 24px in settings (the indicator icons are Skype, Dropbox, Synergy and that battery symbol):

![topiconsplus-24px](https://user-images.githubusercontent.com/29852/33206506-c8df60dc-d10a-11e7-998e-c6b2904d2013.png)

This extension with the +6px change:

![appindicator- 6px](https://user-images.githubusercontent.com/29852/33206378-56aa2916-d10a-11e7-9b78-56449449d9e6.png)

This extension with default panel height:

![appindicator- 0px](https://user-images.githubusercontent.com/29852/33206399-60039f2e-d10a-11e7-9bd9-eab4b03c54ba.png)

Topicon isn't so bad, but dropbox looks strangely blown up and the battery icon is also pretty large. The +6px version of this extension just makes the icons look totally out of place.

Actually the default height version looks best to me: Everything is crisp and all icons have a consistent size with the exception of the dropbox icon appearing a bit small. But that's actually the fault of the (default) icon itself, which has 1px free at the top and bottom, then 2 pixel grayish transparency which is not really visible on the dark background of the panel:

![dropboxstatus-idle](https://user-images.githubusercontent.com/29852/33206769-a2c1fbfc-d10b-11e7-99e7-8d0a7da2e964.png)

**Comment by jhasse** [comment]
Thanks again for your extensive testing.

It looks like TopIcons doesn't do any scaling. That's why the 24px settings uses the 16px icons. Can you confirm?

I've just tried Synergy and it doesn't look as blurry as in your screenshot for me. Can you try if using the default GNOME Shell theme changes anything for you?

Not doing any scaling if the provided icons are "about" the correct size sounds like a good fix for me, what do you think? (16px and scaling down doesn't work for some icons, like Telegram with an unread counter)

**Comment by phw** [comment]
> It looks like TopIcons doesn't do any scaling. That's why the 24px settings uses the 16px icons. Can you confirm?

Not sure what it does, maybe it does just not scale the pixel icons? But yes, Synergy and Skype icons they are definitely not scaled when I compare the screenshots in GIMP.

> I've just tried Synergy and it doesn't look as blurry as in your screenshot for me. Can you try if using the default GNOME Shell theme changes anything for you?

It could also be the icon. I just saw that the Synergy git repository contains a "synergy.svg" file, but the stable release 1.8 only contains the .ico file.

I read through #68, this whole issue with icon sizes seems to be pretty messy. I had previously already tried changing the shell theme to default (I use Arc-Dark currently), and it didin't make a difference. But maybe I should restart the shell and extensions, will try again. Also I do set `XDG_CURRENT_DESKTOP=Unity`, but only for some icons. Have to check, but I think I needed this for Dropbox and Skype to show up at all. This could also make some difference.

**Comment by robfrawley** [comment]
> > People find the 16px size to small, see #68.
>
> Why would I want the app indicator icons to be larger then the rest of my panel icons? That doesn't make much sense.

_Exactly!_ I honestly still don't understand the mind-set behind #68, even after reading through its entire comment thread.

The enlarged icons are jarring and out of place with the core icons sitting right next to them (battery, volume, wireless, and any other icons rendered using the native gnome indicator handling). My expectation is that all the indicator icons, regardless of whether they are rendered through _this extension_ **or** they are rendered through the _native gnome indicator handling_, should be **rendered with the same height**, so that all my indicators form a sensible, consistant, and cohesive row of icons.

The absolute best-case scenario would be that I simply _cannot tell which indicator icons were rendered from this extension and which were rendered with the native gnome handling_. Prior, this extension was close to that goal; it wasn't perfect, but close. Sadly, the changes introduced in #68 make it painfully obvious which indicator icons are rendered outside of the native gnome handling due to the sizing differences.
