### ISSUE TITLE
Change position of this extension

### ISSUE THREAD

**Issue by sojusnik** [ubuntu/gnome-shell-extension-appindicator#148]
On my Ubuntu 18.04 this extension appears [between two indicators](https://i.imgur.com/leMD2OV.png), but I prefer to have it always on the left end. This was possible to achieve in [TopIcons Plus](https://github.com/phocean/TopIcons-plus) by tinkering with "tray horizontal alignment" and "tray offset" in the settings. Would be very useful to have it in this extension too!

I'm coding illiterate, but it seems convenient to port it. Just have a look on `placeTray` in the [extension.js](https://github.com/phocean/TopIcons-plus/blob/41f1a9b5dcf4b0c92ffce378b3e772253be479e5/extension.js). [This](https://askubuntu.com/questions/453969/how-can-i-order-gnome3-shell-extensions-at-the-top/661015#661015) and [this](https://www.reddit.com/r/gnome/comments/9gj3c8/can_i_reorder_the_icons_on_the_system_tray/e66qgct) link could help too.

**Comment by lestcape** [comment]
Change the position of a panel button is really not possible in an extension, because there are not way actually to do that in the shell: https://gitlab.gnome.org/GNOME/gnome-shell/issues/402. 

Whatever you will implement, it will fail or will have a big possibility to fail to someone else, because you and another user have not the same extensions enables, so for one the extension will be enable in the position 5, but for the another the correct position could be the 8.

Just think for example that you find a way to load this extension in the specific position you want, but then i wrote another extension and i want the same position and also other 5 extensions more want the same position. That will be just a crazy war to win that requested position for sure. And some extension will fail to gain that position for sure and you can not be sure of what of those extension will be the winner.

Also please imagine that i open another issue here to also change the position, because i like another different position and not the position you propose. So, please can you tell me what we can do in that case? How we can have what we want both at the same time?

Is crazy right? I recommend you that close this issue and join to us in the gnome-shell request. There are only one way to solve that issue in a general way and this is in gnome shell, not here.

**Comment by sojusnik** [comment]
> Also please imagine that i open another issue here to also change the position, because i like another different position and not the position you propose. So, please can you tell me what we can do in that case? How we can have what we want both at the same time?

TopIcons Plus actually provides a way to adjust the position to your liking in the settings. Of course this is not a proper solution, but a hackish workaround and the best way we have today. Since the code is already present, why not use it in this extension too?

From a global perspective you're totally right: Fiddling around in such a way is not the optimal way – it leads to complexity and therefore to unreliable solutions. But why not use this way in the meantime and hope that the Gnome devs will finally recognize the necessity of such a feature.

**Comment by lestcape** [comment]
> But why not use this way in the meantime and hope that the Gnome devs will finally recognize the necessity of such a feature.

You already know why... :)

this is an Ubuntu extension and the Ubuntu developers are also part of the gnome upstream, so i think they have the opportunity to do the things in a right way, then why they should do something for "_the meantime_"?

If you already agree that this will not be a proper solution, why not request a proper one instead of workarounds?

**Comment by sojusnik** [comment]
Ok, so let's hope for an upstream fix.
