### ISSUE TITLE
Nextcloud icon missing in gnome 3.34

### ISSUE THREAD

**Issue by uncles-a-m** [ubuntu/gnome-shell-extension-appindicator#190]
After updating to Gnome 3.34 on Arch, the Nexcloud icon is missing. Update to the newest version of the extension didn't solve the issue.

**Comment by epsilontheta** [comment]
For me `libappindicator-gtk3` was missing.
After installing it everything worked as expected.

**Comment by uncles-a-m** [comment]
Thanks for your comment, epsilontheta. 
`libappindicator-gtk3 ` is installed on my system but the nextcloud icon is missing nevertheless.

**Comment by unholyeyebrows** [comment]
Hi, I have the same issue with Ubuntu 19.10 Eoan Beta.

**Comment by epsilontheta** [comment]
I think it is a timing related problem. When logging in and having nextcloud in autostart there is no icon. When stopping nextcloud, e.g. with ´killall nextcloud`, and manually starting it the icon appears. Can you reproduce this?

**Comment by unholyeyebrows** [comment]
Hi - this doesn't help on Ubuntu Eoan i.e regardless of whether the client is started automatically or manually I never get the icon.

**Comment by uncles-a-m** [comment]
epsilontheta, I can reproduce this behaviour. When I kill nextcloud and start it manually afterwards, the icon is shown as expected.

**Comment by kas7yler** [comment]
Same with copyq & goldendict. No icon if auto-started, but launching manually works.

**Comment by jhasse** [comment]
I think this is a duplicate of #98. Feel free to reopen.

**Comment by marbx** [comment]
I have just set up Debian 11 with Gnome 3.38.5 on a new laptop.

The NextCloud systray icon is missing, which is strange because I use the same setup as for my current laptop.

After exiting NextCloud and starting again the systray icon appears.

NextCloud is started by a *.desktop file.

The *.desktop file seems to have no "delayed start" option
https://specifications.freedesktop.org/desktop-entry-spec/latest/


I therefore use `sleep 2` with this workaround
```
$ grep Exec  .config/autostart/com.nextcloud.desktopclient.nextcloud.desktop 
Exec=/usr/bin/nextcloudSleep.sh

$ cat /usr/bin/nextcloudSleep.sh 
sleep 2 
/usr/bin/nextcloud --background
```

With this workaround, the systray icon appears after a delay of 2 seconds after login.


The `.config/autostart/com.nextcloud.desktopclient.nextcloud.desktop` file will probably be overwritten with the next NextCloud update.
