### ISSUE TITLE
Fixed size indicators

### ISSUE THREAD

**Issue by andia89** [ubuntu/gnome-shell-extension-appindicator#211]
After the latest changes, it seems that icons do have a fixed size again
![Screenshot from 2020-03-13 09-30-24](https://user-images.githubusercontent.com/6475757/76603603-8941ea00-650d-11ea-9a5f-abf30d7d4913.png)

the three extensions with text (they are custom made) all have a 1px white transparent svg icon, but it shows up as an icon with normal width, taking up way too much space. 

Additionally now most of the icons seems way too small (dropbox for example) compared to icons that are from gnome-shell extensions directly (caffeine for example)

**Comment by spielkind** [comment]
Seem to small for me as well: https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/205#issuecomment-598384773

**Comment by 3v1n0** [comment]
Please, feel free to give me the code of those text-only indicators so that I can test them also (I didn't notice in the ones I had here), but as expressed in https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/205#issuecomment-598680374 the icon size is just matching what gnome-shell expects, so I consider this actually a fix.

So I'm not closing this issue, but only addressing the text-indicators case, while icon sizes are now managed by the indicators themselves, and if they provided a too-small-icon (many included padding) these are the ones to fix.

**Comment by andia89** [comment]
```#!/usr/bin/python3
import gi
gi.require_version('AppIndicator3', '0.1')
gi.require_version('Gtk', '3.0')
import os
import tempfile
from gi.repository import Gtk as gtk
from gi.repository import GLib
from gi.repository import AppIndicator3 as appindicator



APPINDICATOR_ID = 'test'
fn, tindicator = tempfile.mkstemp(suffix=".svg")

with open(tindicator, "w") as f:
    svg = '<?xml version="1.0" encoding="UTF-8" \
           standalone="no"?><svg id="empty" xmlns="http://www.w3.org/2000/svg" \
           height="22" width="1" version="1.0" \
           xmlns:xlink="http://www.w3.org/1999/xlink"></svg>'
    f.write(svg)
    f.close()


class TestIndicator:
    def __init__(self):
        self.indicator = appindicator.Indicator.new(APPINDICATOR_ID, tindicator, appindicator.IndicatorCategory.SYSTEM_SERVICES)
        self.indicator.set_status(appindicator.IndicatorStatus.ACTIVE)
        self.indicator.set_menu(self.build_menu())
        self.indicator.set_label("test: width", "")
        
    def main(self):
        gtk.main()
    
    def build_menu(self):
        menu = gtk.Menu()
        item_quit = gtk.MenuItem('Quit')
        item_quit.connect('activate', self.quit)
        
        menu.append(item_quit)
        menu.show_all()
        return menu
        

    def quit(self, source):
        self.stop = True
        gtk.main_quit()
        os.remove(tindicator)

if __name__ == "__main__":
    c = TestIndicator()
    c.main()```

that would be a minimum working example. 

I see the point on the icon size, I think once all the icons will be adapted it will look fine

**Comment by Eonfge** [comment]
![Screenshot from 2020-03-14 12-35-57](https://user-images.githubusercontent.com/33983090/76681180-6a685400-65f0-11ea-88fa-19f89cd630a0.png)

The icons of Spideroak (cloud with arrow) and Variety (square with mountain in it) now appear smaller then those of other extensions. For reference. I'm running Freon on the left and Clipboard Indicator on the right.

System:
Fedora 31
GNOME 3.34

Also visible: 
Dash To Panel

**Comment by shibotto** [comment]
![Schermata da 2020-03-15 11-15-54](https://user-images.githubusercontent.com/3816409/76699520-6c90e800-66ae-11ea-8f87-7227196bfb6a.png)
The telegram-desktop icon, I have to squint a lot to be able to read the number in the red circle. If I may express a preference, different sizes icons are less of an eyesore than blurry ones.

**Comment by romm1of** [comment]
![image](https://user-images.githubusercontent.com/19668606/76969997-dd950180-6933-11ea-8298-763c17d01c50.png)

Slack icon seems small comparing to the others, wish I could set manually the size of the icons. 

Arch + Gnome 3.36 w/ Dash To Panel extension

**Comment by aelrindel** [comment]
Hello @3v1n0 

This last update however has made the extension unusable for me since all the icons are barely readable, especially if they contains text or numbers (such as Telegram or Slack).

I understand that the new behavior is more correct on paper, but I still feel like breaking user space is wrong, regardless of the reason.

As the users didn't get any kind of notice or migration option from old and new behavior, it wasn't even possible for us to go down the path you suggested (i.e.: warning application developers to update their code).

This was too sudden, and basically put the users in a bad place; this is sadly a recurring theme within GNOME projects (and the reason we need an extension for tray icons in the first place).

I hope in the future you will consider adding an option for users that would like to customize the icon size.

Thanks again for your work, which has proven really useful for me!

**Comment by 3v1n0** [comment]
Icons sizes are now configurable from extensions preferences, so this can be closed.
