### ISSUE TITLE
Legacy X11 tray-icons are too small

### ISSUE THREAD

**Issue by jwrdegoede** [ubuntu/gnome-shell-extension-appindicator#299]
The title pretty much says it all, by default legacy tray-icon seems to be significantly smaller then the system icons on the right side of the panel.

Changing the icon size to 22 in the preferences makes the size the same, perhaps this should be the default?

**Comment by 3v1n0** [comment]
The problem here is that is quite hard to know what icon we're getting, so it may be an icon with some padding (and so eventually will look smaller) or not.

Given it's hard to define, I'd prefer to just be consistent and use the same size for all.
In case, I may provide a preference for only tray icons if that's the main issue.
