### ISSUE TITLE
Double-clicking the indicator shows two menus: a Shell and a legacy one

### ISSUE THREAD

**Issue by cassidyjames** [ubuntu/gnome-shell-extension-appindicator#94]
If you double-click an indicator (tested here with Dropbox), it appears you get two menus: one Shell menu (as expected) and then the underlying/legacy menu drawn by the app. It then gets pretty inconsistent/impossible to close both menus without clicking an item in the menu first.

**Comment by jhasse** [comment]
I fear that this needs to be fixed by the Dropbox devs :(

**Comment by cassidyjames** [comment]
If the extension is extracting their menu and redrawing it, how is Dropbox expected to know about that? I don't see how allowing extensions to draw their own menu at all is not a bug with this extension. This bug is also not present with the TopIcons-Plus extension of with the elementary OS Ayatana WingPanel plugin.

**Comment by jhasse** [comment]
I guess that Dropbox thinks that the [`Activate` method](https://github.com/ubuntu/gnome-shell-extension-appindicator/blob/master/interfaces-xml/StatusNotifierItem.xml#L35) only get's called by legacy trays, I wonder how this works on KDE?

> how allowing icons to draw their own menu at all outside of the shell-drawn one is not a bug with this extension

We aren't explicitly allowing it. Dropbox is a binary which can do whatever it wants and we can't prevent that.

It works with TopIcons Plus, since that uses the legacy tray just as GNOME does (before 3.26) and I guess Dropbox devs have tested it with that. About the WingPanel plugin: I guess they don't send the Activate signal on double-click.

**Comment by jhasse** [comment]
If I'm not mistaken this doesn't happen when running Dropbox with `XDG_CURRENT_SESSION=Unity`, see #74.
